# online configuration settings
#==============#
# QuadricSLAM  #
#==============#

QuadricSLAM.zero_prior: False
# prior set to SVD quadric
# NOTE: what if set to unit sphere?
QuadricSLAM.quad_priors: False
QuadricSLAM.quad_prior_sd: 1e3
# prior Q with inf sigma for all but rotation, which has prior 0
QuadricSLAM.prior_rots: True
QuadricSLAM.prior_rots_sd: 1e3
QuadricSLAM.inf_sd: 1e18
#
QuadricSLAM.angle_factors: False
QuadricSLAM.angle_factor_sd: 1e2

QuadricSLAM.gps: False
QuadricSLAM.gps_sd: 0.001
QuadricSLAM.odom_sd: 0.001

QuadricSLAM.n_priors: 2
QuadricSLAM.pose_prior_sd: 1.0

QuadricSLAM.box_sd: 20.0

QuadricSLAM.init_method: "SVD" # SVD, SIMPLE, TRUE
QuadricSLAM.min_views: 3

QuadricSLAM.measurement_model: "STANDARD" # STANDARD, TRUNCATED

QuadricSLAM.filter_measurements: False
QuadricSLAM.viable_classes: ['cup', 'bowl']
QuadricSLAM.classes_path: "/home/lachness/git_ws/PyTorch-YOLOv3/data/coco.names"


#===========#
# Recording #
#===========#
Recording.record: False

#====================#
# Optimizer Settings #
#====================#
Optimizer: "ISAM-D" # ISAM, ISAM-D, LVM, GN
ISAM.factorization: "QR" # CHOLESKY, QR
ISAM.relinearization: True
ISAM.relinearize_skip: 1
ISAM.relinearize_thresh: 0.01

#==================#
# Data-association #
#==================#
DataAssociation.iou_thresh: 0.4
DataAssociation.object_limit: 100
# BOOSTING, MIL, KCF, TLD, MEDIANFLOW, GOTURN, MOSSE, CSRT
DataAssociation.tracker_type: "MEDIANFLOW"
