# online configuration settings
#==============#
# QuadricSLAM  #
#==============#


QuadricSLAM.quad_priors: True
QuadricSLAM.quad_prior_sd: 100

QuadricSLAM.gps: True
QuadricSLAM.gps_sd: 0.001
QuadricSLAM.odom_sd: 0.01

QuadricSLAM.n_priors: 2
QuadricSLAM.pose_prior_sd: 0.01

QuadricSLAM.box_sd: 5.0

QuadricSLAM.init_method: "SVD"
QuadricSLAM.min_views: 5

QuadricSLAM.measurement_model: "STANDARD" # STANDARD, TRUNCATED

QuadricSLAM.filter_measurements: False
QuadricSLAM.viable_classes: ['cup', 'bowl']
QuadricSLAM.classes_path: "/home/lachness/git_ws/PyTorch-YOLOv3/data/coco.names"


#===========#
# Recording #
#===========#
Recording.record: False

#====================#
# Optimizer Settings #
#====================#
Optimizer.dogleg: True
Optimizer.relinearization: True
Optimizer.relinearize_skip: 1
Optimizer.relinearize_thresh: 0.01

#==================#
# Data-association #
#==================#
DataAssociation.iou_thresh: 0.4
DataAssociation.object_limit: 100
# BOOSTING, MIL, KCF, TLD, MEDIANFLOW, GOTURN, MOSSE, CSRT
DataAssociation.tracker_type: "MEDIANFLOW"
