# KITTI monocular model for seq.03

#==============#
# Camera Model #
#==============#

Camera.name: "FULL HD 1080p"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 311.487764
Camera.fy: 311.262275
Camera.cx: 309.428522
Camera.cy: 237.721368

Camera.k1: 0.026040
Camera.k2: -0.044810
Camera.p1: 0.000472
Camera.p2: -0.000658
Camera.k3: 0.0

Camera.fps: 25.0
Camera.cols: 640
Camera.rows: 480

Camera.color_order: "RGB"
