# This workflow builds the Python package, and uploads to PyPI using Twine

name: Build & upload to PyPI

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Make manylinux wheels
        run: |
          TARGET=manylinux2014_x86_64 && \
          docker run --rm -e PLAT=$TARGET -v {{ github.workspace }}:/io \
          quay.io/pypa/$TARGET /io/.github/build-manylinux-wheel
      - name: Install wheel publishing deps
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade twine
      - env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python -m twine upload ./dist/*
